### ISSUE TITLE
Change license to MIT license.

### ISSUE THREAD

**Issue by ioquatix** [franckverrot/blake2#6]
Otherwise it's hard to use and I'll need to remove it from `fingerprint`.

**Comment by franckverrot** [comment]
Hi there.  Sorry I’m late responding, I’m recovering from some minor health issue.  

Is `fingerprint` this gem https://github.com/ioquatix/fingerprint?  Which is later bundled and sold on Mac App Store here https://itunes.apple.com/nz/app/fingerprint/id470866821.  Is this correct?

**Comment by ioquatix** [comment]
Yep

**Comment by franckverrot** [comment]
(I’m assuming the latter (MacOS app) isn’t GPL, I also couldn’t find the information about it anywhere.)  Would you be willing to get a commercial license for bundling this blake2 gem, if this was possible and affordable?  I don’t intend to make money with this gem but also am not a fan of the idea of relicensing it, so if the other contributor is fine with some changes to his Intellectual Property rights, I could grant you the right of using this gem without relicensing.  What do you think?  We can discuss this in private too if you prefer so please send me an email if you prefer.  Thanks!

**Comment by ioquatix** [comment]
The app in the App Store "Fingerprint" app never used the released of fingerprint that contained BLAKE2 integration.

I respect your position. But, I'm not really interested in your proposal. Frankly speaking it doesn't even make enough money to cover costs. As a result, I've removed the BLAKE2 integration.

**Comment by franckverrot** [comment]
I should have been clearer.  “Not intending to make money”  meant allowing the usage of this gem for you at no cost associated, with the right license.

**Comment by ioquatix** [comment]
Thanks for the clarification.

The main issue I have with that is that anyone who wants to use the source code of fingerprint needs to acquire such a license too. It just makes everything way too complicated and encumbers the source code. The only real solutions are (1) remove the GPL code or (2) get an implementation that is MIT licensed. Because I've already done (1), I consider this issue resolved satisfactorily.

**Comment by ioquatix** [comment]
I'll leave you with one more thought:

- GPL is for the freedom of the user.
- MIT is for the freedom of the developer.

Since we are often both, we don't consider it much.

**Comment by franckverrot** [comment]
Yup, I’ve been dealing with licensing for quite a while (as a user, a developer and as the guy who has to deal with due diligence :-)) and start feeling the pain. (Recently dealt with shoryuken and it was a major PITA https://twitter.com/franckverrot/status/1147226805318774784?s=21)

I’ll ask the other contributor, if he agrees to changing the license I’ll update this ticket.  Thanks again for the clarifications and the overall courteous discussion.

**Comment by franckverrot** [comment]
@ioquatix it's done.  I'll release the new gem later this week, I'm still not doing super well.  Thanks!

**Comment by ioquatix** [comment]
@franckverrot I'm so sorry you aren't feeling well, and I appreciate your effort here. If you make me a co-maintainer of this gem I am happy to help.

If there is anything I can do to help, please feel free to reach out to me.

**Comment by franckverrot** [comment]
Thanks a ton.  I am better now, had some things going on and had to take time to recover.

Just released the gem now, and also bumped the major version.  Thanks again!
