### ISSUE TITLE
Convert license to MIT

### ISSUE THREAD

**Issue by franckverrot** [franckverrot/blake2#7]
As discussed in #6, I would like to change the license from GPL to MIT.

Hopefully there’s only one contributor, @grempe : please respond to this issue with “OK”, or “not OK”.  Should you not be OK with the change please respond to the private email I sent you today but feel free to respond here too.

If you’re OK, I’ll change the license ASAP.

Thanks in advance!

**Comment by grempe** [comment]
Sounds fine to me!  Good luck. "OK"
